title: <p align="center">Rajeev Ragha</p>
logo: /assets/img/logo.png
description: A Fullstack Developer with 10+ years of experience.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
